# auto generated by http://bitbucket.org/afarazit/sophie
# domain: {vhost}
# public: {vhost_document_root}

<VirtualHost *:80>
  # Admin email, Server Name (domain name), and any aliases
  ServerAdmin webmaster@{vhost}
  ServerName  www.{vhost}
  ServerAlias {vhost}

  # Index file and Document Root (where the public files are located)
  DirectoryIndex index.php
  DocumentRoot {vhost_document_root}

  # Log file locations
  LogLevel warn
  ErrorLog  /var/www/{vhost}/logs/error.log
  CustomLog /var/www/{vhost}/logs/access.log combined

  <Directory {vhost_document_root}>
     Options FollowSymLinks
     AllowOverride All
     Order allow,deny
     Allow from all
     Require all granted
  </Directory>
</VirtualHost>
